### ISSUE TITLE
Support QuillJS 2.0

### ISSUE THREAD

**Issue by ArbazIrshad** [vueup/vueup-quill#466]
The first beta of QuillJS 2.0 has been released, and it brings a number of new improvements. However, vue-quill currently does not support QuillJS 2.0.

This issue is to inquire about the possibility of updating vue-quill to support QuillJS 2.0. This would allow users to take advantage of the latest features and improvements in QuillJS.

**Comment by hymmyh** [comment]
quill v1.3.7 Security Issue CVE-2021-3163

**Comment by CasperNH** [comment]
I would love to see the update to 2.0 :)

**Comment by nathanchase** [comment]
Quill 2 is now in RC, with full release in March: https://github.com/quilljs/quill/issues/3806#issuecomment-1933250524

**Comment by CasperNH** [comment]
@luthfimasruri I just wanted to hear if you have any plans to update this package to Quill 2.0, when a official release is made?

**Comment by dodgydre** [comment]
I had just taken the vue-quill code and made an offline version which works with quill 2.0.  Can't remember what specifically i changed but seems to be working fine.

I've got an index.js in a quill folder that sets my global options - In here you can also import and register any modules for your project. 
In the main.js or app.js for the project import that file and register the component globally and then you can use it in any of your components the usual way.  Doesn't have any dependencies on quill version this way so you can import any quill >2.0.0 to your project.

Not sure if this vue-quill package will get updated otherwise.

https://gist.github.com/dodgydre/d712f9cf596b281614a727ec5bd53eb0

**Comment by suchorski** [comment]
Want that too... Waiting for Quill 2 Final version

**Comment by aloiseau17** [comment]
Yes, it could be great to know if you plan @luthfimasruri to update this package to Quill v2 🙂

Thank you for your hard work on this package. It's very helpful.

**Comment by FrazeColder** [comment]
Quill 2.0 has been released. Any plans when this repo will be updated?

**Comment by alekswebnet** [comment]
As an alternative solution, I propose to use a tiny component that helps to build editors on top of Vue 3 and Quill 2:
https://github.com/alekswebnet/vue-quilly

**Comment by suchorski** [comment]
@alekswebnet very Nice. I'll take a look. Thanks

**Comment by FrazeColder** [comment]
Any news here?

**Comment by scottagt** [comment]
Hi @luthfimasruri, is this project no longer active?

**Comment by zhuangqingguo** [comment]
2.0👀

**Comment by lamlamla** [comment]
This project is dead, everyone use [https://github.com/alekswebnet/vue-quilly](https://github.com/alekswebnet/vue-quilly) instead
